spring.application.name=CMS

server.port=3004

spring.datasource.url=jdbc:postgresql://localhost:5432/cms_ztech
spring.datasource.username=z_tech
spring.datasource.password=1233
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

jwts.secret=8d48b2713fc26f3be8410399c9c6dcf0a3b38f0d67ff2a3e3e0e900790438ca861458cafd9bc3973d5c06068d3aa49989e4b6505999d93799c53251952e20fd9
