spring.application.name=CMS

server.port=3004

spring.datasource.url=jdbc:postgresql://localhost:5432/cms_ztech
spring.datasource.username=z_tech
spring.datasource.password=1233
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

jwts.secret=8pKu0P9wegxpHOSUKB9Z8+wNY3DLfqWW4trZ5tzo8AdJCSYNWA1jvccwST8h+LS1m/349Mj4lIiofc49htPuRw==
